services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=saestl_db'
      - 'POSTGRES_PASSWORD=saestl_secret'
      - 'POSTGRES_USER=saestl'
    ports:
      - '5433:5432'
