# ===== Profile: docker (PostgreSQL real) =====
# Se activa con: SPRING_PROFILES_ACTIVE=docker

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:saestl_db}
spring.datasource.username=${POSTGRES_USER:saestl}
spring.datasource.password=${POSTGRES_PASSWORD:saestl_secret}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.locations=classpath:db/migration
